version: 2.1
jobs:
  build:
    machine: 
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: 
          name: build!
          command: ./build

workflows:
  version: 2
  build-deploy:
    jobs:
      - build