version: 2.1
jobs:
  build:
    machine: 
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: 
          name: build!
          command: ./build
    environment:
      CIRCLE_TRIGGER: << pipeline.trigger_source >>

workflows:
  version: 2
  build-deploy:
    jobs:
      - build